### ISSUE TITLE
a review of types in Process struct

### ISSUE THREAD

**Issue by tshepang** [borntyping/rust-psutil#14]
There are things that cannot be negative, like `num_threads` and `rss`, yet they have a signed integer as type.

**Comment by borntyping** [comment]
The types try to match those in [`proc(5)`](http://man7.org/linux/man-pages/man5/proc.5.html) as much as possible. I'm not sure if it would be better to keep them this way or convert them into more useful types.

**Comment by tshepang** [comment]
Oh, in that case I'll give this a close.
