### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mivade** [borntyping/rust-psutil#36]
It looks like quite a few features have been added since 1.1.1 was released which I found out the hard way trying to follow examples when using the version of `psutil` installed with cargo. Is there anything holding back a new release?

**Comment by borntyping** [comment]
Released latest version as [version 1.2.0](https://crates.io/crates/psutil/1.2.0). Sorry for the delay!

**Comment by rkday** [comment]
I noticed that the badge on that page still said 'tag v1.1.1', so I've [fixed that](https://github.com/borntyping/rust-psutil/releases/tag/v1.2.0).
