### ISSUE TITLE
Refactor system into separate files

### ISSUE THREAD

**Issue by cjbassi** [borntyping/rust-psutil#46]
Currently the system file includes memory, load average, and cpu functions, but I think it would be good to separate those out. gopsutil separates them and it makes it easier to organize things. However, this would be a breaking change.

edit: gopsutil has a host module that includes things like uptime, which is also in the system file. So maybe we could only include stuff like that and maybe rename it to 'host'.

**Comment by borntyping** [comment]
It should be possible to make these changes without breaking the API by moving functions into separate files while still exporting them in the files they were originally in.

https://doc.rust-lang.org/1.4.0/book/crates-and-modules.html#re-exporting-with-pub-use
