### ISSUE TITLE
Calculating cpu usage of each process?

### ISSUE THREAD

**Issue by shirshak55** [borntyping/rust-psutil#61]
I want to calculate cpu % usage of each process. But how to get hertz count?

Our code look like this:

```
fn main() {
	let processes = psutil::process::all().unwrap();

	let uptime = psutil::host::uptime() as f64;
        let hertz = ?????????????  // Hertz (number of clock ticks per second)

	for process in processes.into_iter() {
		let total_time = process.stime + process.utime + process.cutime + process.cstime;
		let seconds = uptime() as f64 - (process.starttime - hertz);
                let  cpu_usage = 100 * ((total_time / hertz) / seconds)
		dbg!(cpu_usage);
	}
}
```

I think we can get it by getconf CLK_TCK.

https://pubs.opengroup.org/onlinepubs/009695399/utilities/getconf.html.

Any good solution for such case?

By the way i did tried to compile example but may be its not working due to recent update. 

Thanks.

**Comment by shirshak55** [comment]
hmm i used it let me know if there is better way.

```
use libc;

fn get_hertz() -> i64 {
	unsafe { libc::sysconf(libc::_SC_CLK_TCK) }
}

fn main() {
	let processes = psutil::process::all().unwrap();

	let uptime = psutil::host::uptime() as f64;
	let hertz = get_hertz() as f64;
	for process in processes.into_iter() {
		let total_time = process.stime + process.utime + process.cutime + process.cstime;
		let seconds = uptime - (process.starttime);
		let cpu_usage = 100.0 * ((total_time / hertz) / seconds);
		dbg!(process);
	}
}

```

Feel free to close or i will close by 1-2 day. 

Thanks

**Comment by cjbassi** [comment]
So I actually just added per process CPU percent usage on the master branch, but it only works on Linux for now. Give that a try, and let me know if that works for you. If the new API is confusing, then let me know and I can write up an example.

**Comment by shirshak55** [comment]
@cjbassi can u give me small example. I couldn't find where new api is.

**Comment by shirshak55** [comment]
is it this one?
https://github.com/borntyping/rust-psutil/blob/master/src/process/sys/linux/process.rs#L162

**Comment by cjbassi** [comment]
Oh actually heres one already https://github.com/borntyping/rust-psutil/blob/master/examples/ps.rs

**Comment by shirshak55** [comment]
@cjbassi by the way how to get uid from process now?

**Comment by cjbassi** [comment]
Literally just added that to master :). Import `psutil::process:os::unix::ProcessExt` and then you can do `process.uid()?.effective`

**Comment by shirshak55** [comment]
```
pub trait ProcessExt {
	fn uids(&self) -> Vec<Uid>;

	fn gids(&self) -> Vec<Gid>;

	fn terminal(&self) -> Option<String>;

	fn num_fds(&self) -> Count;
}
```

Hmm can we use `?` operator on uids() as it returns Vector of Uid

**Comment by shirshak55** [comment]
i am getting error which says not yet implemented . It has to do with todo right?
```

pub trait ProcessExt {
	fn uids(&self) -> Vec<Uid>;

	fn gids(&self) -> Vec<Gid>;

	fn terminal(&self) -> Option<String>;

	fn num_fds(&self) -> Count;
}

impl ProcessExt for Process {
	fn uids(&self) -> Vec<Uid> {
		todo!()
	}

	fn gids(&self) -> Vec<Gid> {
		todo!()
	}

	fn terminal(&self) -> Option<String> {
		todo!()
	}

	fn num_fds(&self) -> Count {
		todo!()
	}
}
```

**Comment by shirshak55** [comment]
sorry forgot to close :)

**Comment by cjbassi** [comment]
All good :), also, I just set up a matrix room if you prefer to chat that way: https://matrix.to/#/#rust-psutil:matrix.org
